# Generated by Django 6.0.5 on 2026-05-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('budget_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Shoshilinch emas'), ('normal', 'Oddiy'), ('high', 'Tezkor'), ('emergency', 'Favqulodda')], default='normal', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "Aktiv (e'lon qilingan)"), ('matched', 'Usta tanlangan'), ('in_progress', 'Ish davom etyapti'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='published', max_length=15)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ai_extracted_skills', models.ManyToManyField(blank=True, related_name='ai_orders', to='masters.skill')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='masters.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='masters.region')),
                ('selected_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_orders', to='masters.masterprofile')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/')),
                ('order_idx', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
            options={
                'ordering': ('order_idx', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('eta_hours', models.PositiveSmallIntegerField(blank=True, help_text='Necha soatda bajariladi', null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Tanlangan'), ('rejected', 'Rad etilgan'), ('withdrawn', "Usta o'z taklifini qaytarib oldi")], default='pending', max_length=12)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='masters.masterprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_orde_client__16ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['category', 'status'], name='orders_orde_categor_18b0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='orderresponse',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_990a52_idx'),
        ),
        migrations.AddIndex(
            model_name='orderresponse',
            index=models.Index(fields=['master', 'status'], name='orders_orde_master__f484a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderresponse',
            unique_together={('order', 'master')},
        ),
    ]
