# Generated by Django 6.0.5 on 2026-05-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Yuborildi'), ('accepted', 'Qabul qilindi'), ('declined', 'Rad etildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bookings', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bookings', to='masters.masterprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='orders.order')),
            ],
            options={
                'verbose_name': "Band qilish so'rovi",
                'verbose_name_plural': "Band qilish so'rovlari",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['master', 'status', '-created_at'], name='orders_book_master__0bf549_idx'), models.Index(fields=['client', '-created_at'], name='orders_book_client__2e5e3b_idx'), models.Index(fields=['order', 'status'], name='orders_book_order_i_e4c605_idx')],
                'unique_together': {('order', 'master')},
            },
        ),
    ]
