services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  web:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/dev.txt
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/data       # baza alohida volume'da
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/dev.txt
    command: celery -A config worker -l info
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/data
    depends_on:
      - redis

volumes:
  redis_data:
  sqlite_data:
