# Generated by Django 6.0.5 on 2026-05-13 06:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masters.category')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('hourly_rate_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_cache', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('reviews_count_cache', models.PositiveIntegerField(default=0)),
                ('completed_orders_cache', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, verbose_name='Ish qabul qiladimi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Admin tasdiqlagan')),
                ('categories', models.ManyToManyField(blank=True, related_name='masters', to='masters.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta profili',
                'verbose_name_plural': 'Ustalar profili',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='masters.category')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='masters.masterprofile')),
            ],
            options={
                'verbose_name': 'Portfolio elementi',
                'verbose_name_plural': 'Portfolio elementlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='masters.portfolioitem')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('viloyat', 'Viloyat'), ('tuman', 'Tuman')], default='tuman', max_length=10)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'kind': 'viloyat'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masters.region')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='masters', to='masters.region'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text="Sinonimlar — AI matching uchun (masalan: ['kran', 'jo'mrak'])")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='masters.category')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='masters', to='masters.skill'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='masters_cat_parent__0a35e1_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['master', '-created_at'], name='masters_por_master__de2360_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='masters_ski_categor_a7aa69_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['is_available', 'is_approved'], name='masters_mas_is_avai_e65553_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['-rating_cache'], name='masters_mas_rating__2dd4d3_idx'),
        ),
    ]
