# Generated by Django 6.0.5 on 2026-05-25 11:05
# Manually edited to preserve existing single-language data:
#   eski `name`/`bio`/`title`/`description` qiymatlari yangi *_translation
#   jadvallarga language_code='uz' bilan ko'chiriladi, keyin eski ustunlar o'chiriladi.

import django.db.models.deletion
import parler.models
from django.db import migrations, models


# ── Data ko'chirish funksiyalari ──────────────────────────────────────────────
DEFAULT_LANG = "uz"


def _copy_single_field(apps, src_model_name, dst_model_name, fields):
    """`src` modeldagi har bir obyektning `fields` qiymatlarini `dst`
    Translation modelga language_code='uz' bilan ko'chiradi.

    `fields` — list of (src_field_name, dst_field_name) tuples.
    """
    Src = apps.get_model("masters", src_model_name)
    Dst = apps.get_model("masters", dst_model_name)
    to_create = []
    for obj in Src.objects.all():
        kwargs = {dst_name: getattr(obj, src_name, "") or "" for src_name, dst_name in fields}
        kwargs["language_code"] = DEFAULT_LANG
        kwargs["master_id"] = obj.pk
        to_create.append(Dst(**kwargs))
    if to_create:
        Dst.objects.bulk_create(to_create, batch_size=200)


def copy_data_to_translations(apps, schema_editor):
    _copy_single_field(apps, "Category", "CategoryTranslation", [("name", "name")])
    _copy_single_field(apps, "Skill", "SkillTranslation", [("name", "name")])
    _copy_single_field(apps, "Region", "RegionTranslation", [("name", "name")])
    _copy_single_field(apps, "MasterProfile", "MasterProfileTranslation", [("bio", "bio")])
    _copy_single_field(
        apps,
        "PortfolioItem",
        "PortfolioItemTranslation",
        [("title", "title"), ("description", "description")],
    )


def restore_data_from_translations(apps, schema_editor):
    """Backward migration uchun: agar migration orqaga qaytsa, uz tarjimasini
    eski ustunga qaytarib qo'yadi. Bu RemoveField'lar undo bo'lganidan keyin ishlaydi."""
    mapping = [
        ("Category", "CategoryTranslation", [("name", "name")]),
        ("Skill", "SkillTranslation", [("name", "name")]),
        ("Region", "RegionTranslation", [("name", "name")]),
        ("MasterProfile", "MasterProfileTranslation", [("bio", "bio")]),
        ("PortfolioItem", "PortfolioItemTranslation",
         [("title", "title"), ("description", "description")]),
    ]
    for src_name, dst_name, fields in mapping:
        Src = apps.get_model("masters", src_name)
        Dst = apps.get_model("masters", dst_name)
        for tr in Dst.objects.filter(language_code=DEFAULT_LANG):
            try:
                obj = Src.objects.get(pk=tr.master_id)
            except Src.DoesNotExist:
                continue
            for src_field, dst_field in fields:
                setattr(obj, src_field, getattr(tr, dst_field, "") or "")
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        # ── 1) Meta opsiyalari (xavfsiz, ma'lumotga ta'sir qilmaydi) ────────
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('kind',), 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('category',), 'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),

        # ── 2) Translation jadvallarini yaratish ────────────────────────────
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='masters.category')),
            ],
            options={
                'verbose_name': 'Kategoriya Translation',
                'db_table': 'masters_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='masters_category_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MasterProfileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('bio', models.TextField(blank=True, verbose_name="O'zi haqida")),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='masters.masterprofile')),
            ],
            options={
                'verbose_name': 'Usta profili Translation',
                'db_table': 'masters_masterprofile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='masters_masterprofile_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='masters.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio elementi Translation',
                'db_table': 'masters_portfolioitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='masters_portfolioitem_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='masters.region')),
            ],
            options={
                'verbose_name': 'Hudud Translation',
                'db_table': 'masters_region_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='masters_region_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SkillTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='masters.skill')),
            ],
            options={
                'verbose_name': "Ko'nikma Translation",
                'db_table': 'masters_skill_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='masters_skill_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),

        # ── 3) Eski ma'lumotni yangi translation jadvallarga ko'chirish ─────
        migrations.RunPython(copy_data_to_translations, restore_data_from_translations),

        # ── 4) Eski ustunlarni o'chirish ────────────────────────────────────
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
    ]
