# Generated by Django 6.0.5 — faqat PortfolioImage o'zgarishlari
# (parler translation jadvallaridagi versiya-artefakt alterlar olib tashlandi)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_categorytranslation_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Tashqi rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
