# Generated by Django 6.0.5 on 2026-05-13 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('region_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_shown_to_client', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='masters.masterprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='orders.order')),
            ],
            options={
                'ordering': ('-score',),
                'indexes': [models.Index(fields=['order', '-score'], name='matching_or_order_i_c666de_idx')],
                'unique_together': {('order', 'master')},
            },
        ),
    ]
