# Generated by Django 6.0.5 on 2026-06-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatch',
            name='category_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
